In [1]:
import numpy as np

In [11]:
import pandas as pd

In [18]:
a = np.array([[1,2,3,4],[5,6,7,8]])


declaring a array


In [20]:
print(a[0][1])

2


print the elements

arrays can be 1D 2D or 3D

In [22]:
np.zeros(2)


array([0., 0.])

In [23]:
np.empty(2) 
np.ones(2)

array([1., 1.])

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
arr = np.array([2,1,5,3,7,6,8])

In [29]:
np.sort(arr)

array([1, 2, 3, 5, 6, 7, 8])

to sort the array

In [30]:
a = np.array([1,2,4,3,1,6,9,4])
b = np.array([6,3,6,9,1,6,2,8])

In [32]:
np.concatenate((a,b))

array([1, 2, 4, 3, 1, 6, 9, 4, 6, 3, 6, 9, 1, 6, 2, 8])

to merge to arrays 

In [33]:
i = np.array([[6, 8], [4, 8]])
j = np.array([[1, 8]])

In [34]:
np.concatenate((i,j),axis=0)

array([[6, 8],
       [4, 8],
       [1, 8]])

In [37]:
x = a.reshape(4,2)

In [39]:
print(x)

[[1 2]
 [4 3]
 [1 6]
 [9 4]]


to rehape array

In [40]:
a.sum()

30

to sum the elements of the array you can also sum based on index

In [42]:
i.sum(axis=1)

array([14, 12])

In [43]:
a.max()

9

In [46]:
a.min()

1

In [45]:
a.mean()

3.75

broadcasting 

In [47]:
i*2

array([[12, 16],
       [ 8, 16]])

In [48]:
k = np.random.default_rng()

In [51]:
k.random(15)

array([0.18185084, 0.37438411, 0.07100518, 0.15384983, 0.44846791,
       0.06644418, 0.88653274, 0.80830399, 0.90390868, 0.61863665,
       0.22438683, 0.0211429 , 0.76998116, 0.44733315, 0.81345597])

to create random elements in array

In [54]:
unique_values = np.unique(a)
print(unique_values)

[1 2 3 4 6 9]


to print unique values of array

In [55]:
np.flip(a)
print(a)

[1 2 4 3 1 6 9 4]


to reverse a array

In [59]:
np.dot(a,b)

150

In [65]:
np.random.rand(20)

array([0.63586762, 0.43711832, 0.19459954, 0.12517209, 0.03349065,
       0.94321539, 0.50960225, 0.53520644, 0.27223384, 0.43986498,
       0.93488178, 0.12577159, 0.8655497 , 0.31061563, 0.83026544,
       0.85661482, 0.71400778, 0.47684165, 0.6066012 , 0.71770043])

In [64]:
np.random.randn(10)

array([-0.6561233 , -1.25855177,  0.8556286 , -0.71810239, -0.34372602,
        0.693287  ,  0.8873775 , -0.04075605, -0.17830935,  0.78152521])

In [63]:
np.random.randint(5)

4

In [66]:
np.argmax(a)

6

In [67]:
np.argmin(a)

0